### ISSUE TITLE
regarding fetching results

### ISSUE THREAD

**Issue by svshubhm** [maronean/AccessibilityAnalyzer#1]
Hello sir,
I didn't get the part where you mentioned about fetching the results.
like what terminal command is needed to fetch the results or the folder where the results get stored.
 Any help will be appreciated.
Regards!

**Comment by maronean** [comment]
The tool is designed to be run while the device is connected to a computer using Android Debug Bridge (adb) in the Android SDK tools. 

Results for the Application are logged using Log.V (Verbose logging). 

My suggestion is to run the terminal command 'adb -s [device name] logcat' 
You can then pipe that into grep "AccessibilityAnalyzer" which will filter out any device logs that are not related to the tool.

**Comment by svshubhm** [comment]
Sorry sir,
but I followed what you said and tried this command '**adb -s [device name] logcat | grep accessibilityanalyzer**'

but I am just getting some random logs like this 


C:\Users\DELL\Desktop\AccessibilityA>adb -s ee3647fa logcat | grep accessibilityanalyzer
02-01 16:10:50.054  3774  4256 D GridItemProvider: saveToolBoxItemsToPreference: jsonStr= [{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["andro
id.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.apps.chrome.Main","mPackage":"com.android.chrome"},"mContentUserHint":-2,"mFlags":270532608,"mPa
ckage":"com.android.chrome"},"itemType":0,"launchCount":2297,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["andr
oid.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.gm.ConversationListActivityGmail","mPackage":"com.google.android.gm"},"mContentUserHint":-2,"mF
lags":270532608,"mPackage":"com.google.android.gm"},"itemType":0,"launchCount":618,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN
","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.maronean.andy.accessibilityanalyzer.MainActivity","mPackage":"com.maronean.andy.accessib
ilityanalyzer"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.maronean.andy.accessibilityanalyzer"},"itemType":0,"launchCount":6,"restored":0,"serialNumber":0
},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.snapchat.android.LandingPageAct
ivity","mPackage":"com.snapchat.android"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.snapchat.android"},"itemType":0,"launchCount":1755,"restored":0,"seria
lNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.whatsapp.Main","mPack
age":"com.whatsapp"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.whatsapp"},"itemType":0,"launchCount":29714,"restored":0,"serialNumber":0},{"id":0,"intent"
:{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.sbi.SBIFreedomPlus.sbunifiedcug","mPackage":"com.
sbi.SBIFreedomPlus"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.sbi.SBIFreedomPlus"},"itemType":0,"launchCount":79,"restored":0,"serialNumber":0},{"id":0,"
intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.instagram.android.activity.MainTabActivity
","mPackage":"com.instagram.android"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.instagram.android"},"itemType":0,"launchCount":6504,"restored":4,"serialNu
mber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.youtube.a
pp.honeycomb.Shell$HomeActivity","mPackage":"com.google.android.youtube"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.google.android.youtube"},"itemType":0,
"launchCount":1622,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent
":{"mClass":"com.moba.unityplugin.MobaGameMainActivity","mPackage":"com.mobile.legends"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.mobile.legends"},"itemT
ype":0,"launchCount":1178,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mCo
mponent":{"mClass":"com.oneplus.camera.OPCameraActivity","mPackage":"com.oneplus.camera"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.oneplus.camera"},"item
Type":0,"launchCount":4318,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mC
omponent":{"mClass":"com.oneplus.contacts.activities.OPDialtactsActivity","mPackage":"com.android.dialer"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.andro
id.dialer"},"itemType":0,"launchCount":3947,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.catego
ry.LAUNCHER"],"mComponent":{"mClass":"com.ji
02-01 16:12:42.792  3774  3774 D Stats   : Intent.getPackage() is null. therefore try to get package name from componentName.getPackageName(): com.maronean.andy.accessib
ilityanalyzer
02-01 16:12:42.871  3774  4256 D GridItemProvider: saveToolBoxItemsToPreference: jsonStr= [{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["andro
id.intent.category.LAUNCHER"],"mComponent":{"mClass":"jp.naver.line.android.activity.SplashActivity","mPackage":"jp.naver.line.android"},"mContentUserHint":-2,"mFlags":2
70532608,"mPackage":"jp.naver.line.android"},"itemType":0,"launchCount":15,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCate
gories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.apps.chrome.Main","mPackage":"com.android.chrome"},"mContentUserHint":-2,"mFlags"
:270532608,"mPackage":"com.android.chrome"},"itemType":0,"launchCount":2297,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCat
egories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.gm.ConversationListActivityGmail","mPackage":"com.google.android.gm"},"mContentU
serHint":-2,"mFlags":270532608,"mPackage":"com.google.android.gm"},"itemType":0,"launchCount":618,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.int
ent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.maronean.andy.accessibilityanalyzer.MainActivity","mPackage":"com.maronea
n.andy.accessibilityanalyzer"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.maronean.andy.accessibilityanalyzer"},"itemType":0,"launchCount":6,"restored":0,"
serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.snapchat.android
.LandingPageActivity","mPackage":"com.snapchat.android"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.snapchat.android"},"itemType":0,"launchCount":1755,"res
tored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.whatsa
pp.Main","mPackage":"com.whatsapp"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.whatsapp"},"itemType":0,"launchCount":29714,"restored":0,"serialNumber":0},{
"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.sbi.SBIFreedomPlus.sbunifiedcug","
mPackage":"com.sbi.SBIFreedomPlus"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.sbi.SBIFreedomPlus"},"itemType":0,"launchCount":79,"restored":0,"serialNumbe
r":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.instagram.android.activity.
MainTabActivity","mPackage":"com.instagram.android"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.instagram.android"},"itemType":0,"launchCount":6504,"restor
ed":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.an
droid.youtube.app.honeycomb.Shell$HomeActivity","mPackage":"com.google.android.youtube"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.google.android.youtube"
},"itemType":0,"launchCount":1622,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHE
R"],"mComponent":{"mClass":"com.moba.unityplugin.MobaGameMainActivity","mPackage":"com.mobile.legends"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.mobile.l
egends"},"itemType":0,"launchCount":1178,"restored":4,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.
LAUNCHER"],"mComponent":{"mClass":"com.oneplus.camera.OPCameraActivity","mPackage":"com.oneplus.camera"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.oneplus
.camera"},"itemType":0,"launchCount":4318,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category
.LAUNCHER"],"mComponent":{"mClass":"com.onep
^C

**Comment by svshubhm** [comment]
Okay I found the issue, 
 In the AndroidManifest.xml file 
line no. 25 needs to be changed 
from  **android:name="com.maronean.andy.accessibilityanalyzer.AccessibilityChecker"**

to
 **android:name="com.maronean.andy.accessibilityanalyzer.AccessibilityAnalyzerService"**

**Comment by maronean** [comment]
Hmm. In that case I will have to do some testing. I haven't tested with the newer versions of Android and I know Accessibility services have gotten locked down somewhat since I first developed this. Would you be able give some details: (Device your using, Android Version)

**Comment by svshubhm** [comment]
I am using OnePlus 5T with Android 9.
I built the code without recommended changes.

The code works perfectly fine, just needed the mentioned change
